name: Deploy Frontend

on:
  push:
    paths:
      - 'frontend/**'
      - 'devops/github-actions/frontend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t vitalpath-frontend ./frontend
          docker tag vitalpath-frontend vitalpathregistry.azurecr.io/vitalpath-frontend:latest
          docker push vitalpathregistry.azurecr.io/vitalpath-frontend:latest

      - name: Restart Frontend App Service
        run: |
          az webapp restart --name vitalpath-frontend --resource-group vitalpath-frontend_group