name: Build and Deploy Frontend (VitalPath 2.0)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend   # 👈 Correct context (frontend folder)
          file: ./frontend/Dockerfile  # 👈 Correct Dockerfile path
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/vitalpathfrontend:${{ github.sha }}

      - name: Deploy to Azure Web App (Frontend)
        uses: azure/webapps-deploy@v3
        with:
          app-name: vitalpath-frontend  # Azure App Service name
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/vitalpathfrontend:${{ github.sha }}
