# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - vitalpath-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://vitalpathregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_edbc7ffd563a46d980da55f6492f2fb0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5daed3e184cf41c2a276ad4b24c50fd0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: vitalpathregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_edbc7ffd563a46d980da55f6492f2fb0 }}/vitalpathfrontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vitalpath-frontend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d22b8492179e4369a91cd387ae54ae9d }}
        images: 'vitalpathregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_edbc7ffd563a46d980da55f6492f2fb0 }}/vitalpathfrontend:${{ github.sha }}'