name: Build and Deploy VitalPath Backend to ACA

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: vitalpathregistry.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: vitalpathregistry.azurecr.io/vitalpathbackend:latest

    - name: Deploy to Azure Container Apps (ACA)
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az containerapp update \
            --name vitalpath-backend \
            --resource-group vitalpath-backend_group \
            --image vitalpathregistry.azurecr.io/vitalpathbackend:latest
