name: Deploy Frontend to Azure App Service (Docker)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend Container

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}" | docker login \
            ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }} \
            -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image for frontend
        run: |
          docker build -t vitalpath-frontend ./frontend

      - name: Tag Docker image
        run: |
          docker tag vitalpath-frontend:latest \
            ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/vitalpath-frontend:latest

      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/vitalpath-frontend:latest

      - name: Deploy to Azure App Service (via Publish Profile)
        uses: azure/webapps-deploy@v2
        with:
          app-name: vitalpath-frontend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D22B8492179E4369A91CD387AE54AE9D }}
          images: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/vitalpath-frontend:latest

        




