name: Build and Deploy VitalPath Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  id-token: write
  contents: read    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: vitalpathregistry.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Frontend Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: vitalpathregistry.azurecr.io/vitalpathfrontend:latest

    - name: Deploy Frontend to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'vitalpath-frontend'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
        images: vitalpathregistry.azurecr.io/vitalpathfrontend:latest
