name: Deploy Frontend Container to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend Container

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub (optional, if you're using private base image)
        run: echo "Skip if not needed"

      - name: Build Docker image
        run: docker build -t vitalpath-frontend ./frontend

      - name: Deploy to Azure Web App (container)
        uses: azure/webapps-deploy@v2
        with:
          app-name: vitalpath-frontend
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D22B8492179E4369A91CD387AE54AE9D }}
          images: vitalpath-frontend



