name: Deploy Frontend to Azure App Service (Docker)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Container to Azure App Service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure using Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry (ACR)
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login vitalpathregistry.azurecr.io \
            --username ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t vitalpath-frontend ./frontend

      - name: Tag Docker image
        run: |
          docker tag vitalpath-frontend:latest vitalpathregistry.azurecr.io/vitalpath-frontend:latest

      - name: Push image to ACR
        run: |
          docker push vitalpathregistry.azurecr.io/vitalpath-frontend:latest

      - name: Deploy container to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: vitalpath-frontend
          images: vitalpathregistry.azurecr.io/vitalpath-frontend:latest

        




