name: Deploy Frontend to Azure App Service (Docker)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Container to Azure

    steps:
      - name: ⏬ Checkout code
        uses: actions/checkout@v4

      - name: 🔐 Log in to Azure using publish profile
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: 🏗️ Build Docker image for frontend
        run: |
          docker build -t vitalpath-frontend:${{ github.sha }} ./frontend

      - name: 🏷️ Tag Docker image for ACR
        run: |
          docker tag vitalpath-frontend:${{ github.sha }} \
            ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/vitalpath-frontend:${{ github.sha }}

      - name: 🔑 Log in to ACR
        run: |
          echo "${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}" | docker login \
            ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }} \
            -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin

      - name: 📤 Push image to ACR
        run: |
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/vitalpath-frontend:${{ github.sha }}

      - name: 🚀 Deploy container to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: vitalpath-frontend
          images: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/vitalpath-frontend:${{ github.sha }}




