name: Deploy Frontend Container to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend Container

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure using publish profile
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D22B8492179E4369A91CD387AE54AE9D }}

      - name: Build Docker image
        run: |
          docker build -t vitalpath-frontend:latest ./frontend

      - name: Push image to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: vitalpath-frontend
          slot-name: production
          images: vitalpath-frontend:latest


