name: Deploy Frontend to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Container to Azure

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure using publish profile
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Build Docker image
        run: |
          docker build -t vitalpath-frontend ./frontend

      - name: Tag Docker image for Azure
        run: |
          docker tag vitalpath-frontend:latest vitalpathregistry.azurecr.io/vitalpath-frontend:latest

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}" | docker login \
            vitalpathregistry.azurecr.io \
            -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin

      - name: Push image to Azure Container Registry
        run: |
          docker push vitalpathregistry.azurecr.io/vitalpath-frontend:latest

      - name: Deploy container to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: vitalpath-frontend
          images: vitalpathregistry.azurecr.io/vitalpath-frontend:latest






